#!/bin/sh

#--------------------------------------------------------------------------------------
## Copyright (C) 2010- Alexey Petrov
## Copyright (C) 2009-2010 Pebble Bed Modular Reactor (Pty) Limited (PBMR)
## 
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
## 
## See http://sourceforge.net/projects/pythonflu
##
## Author : Alexey PETROV
##


#--------------------------------------------------------------------------------------
confflu_path=""

if test "x${CONFFLU_ROOT_DIR}" != "x"; then
   confflu_path=${CONFFLU_ROOT_DIR}
fi

if test "x${confflu_path}" = x && test -f /usr/local/share/confFlu/build_configure; then
   confflu_path=/usr/local/share/confFlu
fi

if test "${confflu_path}x" = "x"; then
   echo "ERROR:confFlu need to be installed or sourced"
   exit 0
fi


#--------------------------------------------------------------------------------------
pythonflu_include=""

if test "x${PYTHONFLU_ROOT_DIR}" != "x"; then
   pythonflu_include="-I ${PYTHONFLU_ROOT_DIR}/admin"
fi

if test "x${pythonflu_include}" = "x" && test -d /usr/local/share/pythonFlu/admin; then
   pythonflu_include="-I /usr/local/share/pythonFlu/admin"
fi

if test "${pythonflu_include}x" = "x"; then
   echo "ERROR:pythonFlu need to be installed or sourced"
   exit 0
fi


#--------------------------------------------------------------------------------------
foam2vtk_include=""

if test "x${FOAM2VTK_ROOT_DIR}" != "x"; then
   foam2vtk_include="-I ${FOAM2VTK_ROOT_DIR}/admin"
fi

if test "x${foam2vtk_include}" = x && test -d /usr/local/share/foam2vtk/admin; then
   foam2vtk_include="-I /usr/local/share/foam2vtk/admin"
fi

if test "${foam2vtk_include}x" = "x"; then
   echo "ERROR:foam2vtk need to be installed or sourced"
   exit 0
fi


#--------------------------------------------------------------------------------------
unv2foam_include=""

if test "x${UNV2FOAM_ROOT_DIR}" != "x"; then
   unv2foam_include="-I ${UNV2FOAM_ROOT_DIR}/admin"
fi

if test "x${unv2foam_include}" = x && test -d /usr/local/share/unv2foam/admin; then
   unv2foam_include="-I /usr/local/share/unv2foam/admin"
fi

if test "${unv2foam_include}x" = "x"; then
   echo "ERROR:unv2foam need to be installed or sourced"
   exit 0
fi


#--------------------------------------------------------------------------------------
foam2med_include=""

if test "x${FOAM2MED_ROOT_DIR}" != "x"; then
   foam2med_include="-I ${FOAM2MED_ROOT_DIR}/admin"
fi

if test "x${foam2med_include}" = x && test -d /usr/local/share/foam2med/admin; then
   foam2med_include="-I /usr/local/share/foam2med/admin"
fi

if test "${foam2med_include}x" = "x"; then
   echo "ERROR:foam2med need to be installed or sourced"
   exit 0
fi


#--------------------------------------------------------------------------------------
managedflu_include=""

if test "x${MANAGEDFLU_ROOT_DIR}" != "x"; then
   managedflu_include="-I ${MANAGEDFLU_ROOT_DIR}/admin"
fi

if test "x${managedflu_include}" = "x" && test -d /usr/local/share/managedFlu/admin; then
   managedflu_include="-I /usr/local/share/managedFlu/admin"
fi

if test "${managedflu_include}x" = "x"; then
   echo "ERROR:managedFlu need to be installed or sourced"
   exit 0
fi


#--------------------------------------------------------------------------------------
${confflu_path}/build_configure \
     ${managedflu_include} \
     ${pythonflu_include} \
     ${foam2vtk_include} \
     ${unv2foam_include} \
     ${foam2med_include} \
    -I ${KERNEL_ROOT_DIR}/salome_adm/unix/config_files \
    -I ${GEOM_ROOT_DIR}/adm_local/unix/config_files \
    -I ${MED_ROOT_DIR}/adm_local/unix/config_files \
    -I ${SMESH_ROOT_DIR}/adm_local/unix/config_files \
    -I ${GUI_ROOT_DIR}/adm_local/unix/config_files \
    -I ${VISU_ROOT_DIR}/adm_local/unix/config_files #\
#    -I ${FOAM_ROOT_DIR}/adm_local/unix/config_files


#--------------------------------------------------------------------------------------
