#!/bin/bash

#------------------------------------------------------------------------------
## VulaSHAKA (Simultaneous Neutronic, Fuel Performance, Heat And Kinetics Analysis)
## Copyright (C) 2009-2010 Pebble Bed Modular Reactor (Pty) Limited (PBMR)
## 
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
## 
## See https://vulashaka.svn.sourceforge.net/svnroot/vulashaka/ifoam
##
## Author : Alexey PETROV
##


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # run from this directory


#------------------------------------------------------------------------------
./test_unv2foam_standalone.py

./test_unv2foam_embedded.py || exit 1

./test_icoFoam_salome2unv.py || exit 1

./test_icoFoam_smesh2foam.py || exit 1

./test_icoFoam_file.py || exit 1

./test_foam2vtk.py || exit 1

./test_icoFoam_embedded.py #(Segmentation fault)|| exit 1

./test_icoFoam_scratch.py || exit 1

./test_icoFoam_piso_1.py || exit 1

./test_icoFoam_piso_2.py || exit 1

./test_salome_icoFoam.py  || exit 1


#------------------------------------------------------------------------------
